const text = [
    "Jangan pernah menyerah, karena kesuksesan datang kepada mereka yang terus berusaha.",
    "Mimpi besar hanya bisa dicapai dengan langkah kecil yang konsisten.",
    "Setiap kegagalan adalah pelajaran berharga untuk kesuksesan berikutnya.",
    "Hidupmu adalah hasil dari pilihan yang kamu buat, jadi pilihlah dengan bijak.",
    "Kerja keras selalu membuahkan hasil yang setimpal.",
    "Keberanian adalah kunci untuk membuka pintu kesuksesan.",
    "Kegagalan bukan akhir dari segalanya, tapi awal dari sesuatu yang lebih besar.",
    "Jangan takut untuk memulai, setiap langkah adalah kemajuan.",
    "Percayalah pada dirimu sendiri, kamu lebih kuat dari yang kamu kira.",
    "Kesulitan adalah batu loncatan menuju kesuksesan.",
    "Hidup adalah tentang berani mencoba dan tidak takut gagal.",
    "Kesuksesan dimulai dengan satu langkah kecil.",
    "Bersyukurlah atas setiap hari baru yang diberi kesempatan untuk belajar.",
    "Jangan menunggu kesempatan datang, ciptakan kesempatan itu.",
    "Tantangan adalah kesempatan untuk menjadi lebih baik.",
    "Hidupmu, aturanmu. Jangan biarkan orang lain mendikte perjalananmu.",
    "Kamu tidak akan pernah tahu seberapa kuat kamu sampai menjadi kuat adalah satu-satunya pilihanmu.",
    "Setiap kesulitan pasti ada jalan keluar.",
    "Kesuksesan adalah hasil dari persiapan, kerja keras, dan belajar dari kegagalan.",
    "Jangan takut gagal, takutlah untuk tidak mencoba.",
    "Setiap usaha yang kamu lakukan adalah langkah mendekat ke tujuanmu.",
    "Kamu tidak perlu sempurna untuk memulai, cukup mulai dan perbaiki di sepanjang jalan.",
    "Gagal adalah bagian dari perjalanan menuju sukses, bukan akhir dari segalanya.",
    "Jangan biarkan kegagalanmu mendefinisikan siapa dirimu.",
    "Pikirkan besar, mulailah kecil, dan lakukan dengan penuh semangat.",
    "Hidup ini penuh dengan kesempatan, ambil dan manfaatkan dengan bijak.",
    "Penting untuk berani keluar dari zona nyaman jika ingin mencapai potensi terbaik.",
    "Setiap perjalanan dimulai dengan langkah pertama, ambillah langkah itu.",
    "Kesuksesan bukan tentang apa yang kamu capai, tapi tentang apa yang kamu pelajari.",
    "Satu-satunya cara untuk melakukan pekerjaan besar adalah dengan mencintai apa yang kamu kerjakan.",
    "Jangan biarkan ketakutanmu menghentikanmu untuk mengejar impianmu.",
    "Langkah kecil yang konsisten lebih baik daripada langkah besar yang jarang.",
    "Hidup ini terlalu singkat untuk tidak mencoba hal-hal besar.",
    "Tidak ada jalan pintas menuju kesuksesan, tapi setiap langkah memiliki nilai.",
    "Kamu lebih mampu dari yang kamu pikirkan, teruslah berusaha.",
    "Berhenti menunggu, mulailah bergerak dan lihat bagaimana dunia berubah.",
    "Jangan pernah menyerah hanya karena hasil belum sesuai harapan.",
    "Keberhasilan datang dari kebiasaan baik yang konsisten.",
    "Jika kamu tidak bisa terbang, berlarilah. Jika kamu tidak bisa berlari, berjalanlah.",
    "Jadilah cahaya bagi dunia, bahkan di saat-saat paling gelap sekalipun.",
    "Keberanian untuk melangkah adalah setengah dari perjalanan.",
    "Tidak ada yang bisa mengalahkan semangat yang tidak kenal lelah.",
    "Kesuksesan bukan hanya tentang mencapai tujuan, tapi tentang perjalanan yang kamu tempuh.",
    "Bangkitlah setiap kali kamu jatuh, karena kegagalan hanya menguatkanmu.",
    "Ketika satu pintu tertutup, pintu lain akan terbuka.",
    "Bersyukurlah untuk apa yang kamu miliki, dan berusaha untuk yang lebih baik.",
    "Fokus pada proses, bukan hanya hasil.",
    "Jangan pernah meremehkan potensi yang ada dalam dirimu.",
    "Jangan takut untuk mengejar impianmu, bahkan jika itu terasa sulit.",
    "Keberhasilan bukan tentang berapa banyak yang kamu punya, tapi tentang siapa dirimu.",
    "Tidak ada yang sia-sia dalam usaha yang kamu lakukan.",
    "Terkadang langkah mundur adalah cara untuk melompat lebih jauh.",
    "Jangan biarkan ketidakpastian menghalangi langkahmu.",
    "Kemenangan datang kepada mereka yang tidak pernah berhenti mencoba.",
    "Setiap hari adalah kesempatan baru untuk menjadi lebih baik.",
    "Hidup ini penuh dengan peluang, ambil dan manfaatkan setiap kesempatan yang ada.",
    "Jangan pernah takut untuk mengambil risiko, karena itulah yang membawa perubahan.",
    "Teruslah berjalan, meskipun jalanmu penuh dengan rintangan.",
    "Terkadang kamu perlu mundur untuk melangkah lebih maju.",
    "Keberhasilan adalah hasil dari ketekunan, bukan keberuntungan.",
    "Percaya pada dirimu adalah langkah pertama menuju pencapaian.",
    "Jadilah versi terbaik dari dirimu sendiri setiap hari.",
    "Kegagalan bukanlah akhir, itu adalah pelajaran.",
    "Jika kamu ingin sesuatu yang belum pernah kamu miliki, lakukan sesuatu yang belum pernah kamu coba.",
    "Tahan segala badai, karena setelah hujan datang pelangi.",
    "Setiap kegagalan adalah batu loncatan menuju kesuksesan yang lebih besar.",
    "Hidup adalah tentang mengambil risiko dan belajar dari setiap pengalaman.",
    "Jangan ragu untuk mencoba, karena keberhasilan dimulai dari percobaan.",
    "Untuk sukses, kamu harus terlebih dahulu percaya bahwa kamu bisa.",
    "Kesuksesan itu bukan tentang seberapa banyak kamu memiliki, tapi tentang seberapa banyak yang kamu beri.",
    "Jangan berhenti berusaha hanya karena hasilnya belum sesuai harapan.",
    "Pahami bahwa kegagalan adalah bagian dari perjalanan menuju keberhasilan.",
    "Sabar adalah kunci untuk mencapai impian besar.",
    "Kesuksesan tidak datang dengan mudah, tapi itu layak diperjuangkan.",
    "Berusaha lebih keras adalah jalan menuju impian yang lebih besar.",
    "Bangkitlah setelah kegagalan, karena di situlah kekuatanmu diuji.",
    "Jangan pernah menyerah, karena kamu lebih dekat dengan kesuksesan daripada yang kamu kira.",
    "Keberhasilan datang kepada mereka yang tidak takut untuk gagal.",
    "Teruslah bergerak maju meski terkadang terasa lambat.",
    "Berikan yang terbaik setiap hari, dan sukses akan mengikuti.",
    "Sukses datang kepada mereka yang percaya dan berusaha keras untuk meraihnya.",
    "Keberanian untuk mencoba adalah langkah pertama menuju pencapaian.",
    "Jika kamu jatuh, bangkitlah lagi. Keberhasilan menunggu di sana.",
    "Berpikir positif akan membawa hasil positif.",
    "Kamu adalah hasil dari keputusan yang kamu buat hari ini.",
    "Jangan takut untuk gagal, karena dari kegagalan kamu akan menemukan jalan menuju keberhasilan.",
    "Setiap tantangan adalah peluang untuk belajar dan tumbuh.",
    "Mulailah hari ini, karena hari ini adalah kesempatan terbaik untuk meraih impianmu.",
    "Kesuksesan adalah perjalanan, bukan tujuan.",
    "Jangan pernah menyerah, karena usaha tidak akan pernah mengkhianati hasil.",
    "Keberhasilan membutuhkan waktu, ketekunan, dan banyak usaha.",
    "Hidupmu akan berubah ketika kamu berani untuk berubah.",
    "Bekerja keras dengan hati yang penuh semangat akan selalu membuahkan hasil.",
    "Jangan biarkan ketakutan menghalangi langkahmu menuju impian.",
    "Setiap langkah kecil membawa kamu lebih dekat ke tujuan besar.",
    "Pikirkan besar, dan buktikan bahwa kamu bisa mencapainya.",
    "Keberhasilan tidak mengenal kata terlambat, yang penting adalah niat dan usaha.",
    "Tantangan bukan penghalang, tapi kesempatan untuk mengasah kemampuan.",
    "Kunci kesuksesan adalah memiliki visi yang jelas dan komitmen yang kuat.",
    "Terus bergerak, bahkan jika itu hanya langkah kecil.",
    "Kesuksesan membutuhkan keberanian untuk bermimpi dan ketekunan untuk mencapainya.",
    "Jangan biarkan keraguan menghentikanmu untuk mencapai impianmu.",
    "Semua orang memiliki potensi untuk sukses, yang dibutuhkan adalah keberanian untuk mengambil langkah pertama.",
    "Hidup ini penuh dengan kesempatan untuk belajar dan tumbuh.",
    "Setiap kesalahan adalah peluang untuk memperbaiki diri.",
    "Bekerja keras dengan penuh dedikasi akan membuahkan hasil yang memuaskan.",
    "Kamu akan melihat hasil dari usaha yang kamu tanam hari ini.",
    "Berikan yang terbaik dalam setiap langkahmu, dan dunia akan memberikan yang terbaik untukmu.",
    "Percayalah bahwa kamu bisa, dan setengah dari perjalanan telah tercapai.",
    "Kesuksesan tidak datang dengan mudah, tapi setiap upaya akan membawa kamu lebih dekat.",
    "Satu langkah maju lebih baik daripada seratus langkah mundur.",
    "Bekerja dengan semangat adalah kunci untuk membuka pintu keberhasilan.",
    "Pikirkan bagaimana kamu akan merasa ketika impianmu menjadi kenyataan.",
    "Jangan biarkan rasa takut menghalangi tujuanmu.",
    "Berani bermimpi besar, dan berani untuk mencapainya.",
    "Setiap pencapaian besar dimulai dengan keputusan untuk mencoba.",
    "Jika kamu ingin hasil yang berbeda, lakukan sesuatu yang berbeda.",
    "Kesuksesan bukan hanya tentang hasil, tapi juga tentang perjuangan dan proses yang dilalui.",
    "Jangan pernah ragu dengan kekuatan dalam dirimu.",
    "Setiap kali kamu merasa lelah, ingatlah mengapa kamu memulainya.",
    "Keberhasilan bukanlah hadiah, itu adalah hasil dari kerja keras dan ketekunan.",
    "Jika kamu bisa memimpikannya, kamu bisa mencapainya.",
    "Teruslah berusaha, bahkan ketika semuanya terasa sulit.",
    "Setiap langkah kecil akan membawa kamu lebih dekat ke tujuan besar.",
    "Sukses dimulai dengan langkah pertama, jadi jangan ragu untuk melangkah.",
    "Hidup ini adalah tentang bagaimana kamu bangkit setelah jatuh, bukan tentang seberapa sering kamu jatuh.",
    "Jangan biarkan masa lalu menentukan masa depanmu.",
    "Keberhasilan datang kepada mereka yang tidak pernah berhenti belajar dan berkembang.",
    "Setiap kesulitan adalah kesempatan untuk menjadi lebih kuat.",
    "Jadilah pribadi yang tidak hanya sukses, tetapi juga bermanfaat bagi orang lain.",
    "Tidak ada yang bisa mengalahkan ketekunan yang tidak kenal lelah.",
    "Kamu adalah penentu jalan hidupmu, jadi buatlah keputusan yang tepat.",
    "Hidup ini adalah kesempatan, jadi manfaatkan setiap momennya.",
    "Jangan pernah menyerah, karena hal besar butuh waktu.",
    "Kesuksesan datang dari usaha yang tak pernah berhenti.",
    "Gagal adalah bagian dari proses menuju sukses.",
    "Setiap hari adalah kesempatan baru untuk berkembang.",
    "Kerja keras mengalahkan bakat ketika bakat tidak bekerja keras.",
    "Jangan takut bermimpi besar.",
    "Kamu lebih kuat dari yang kamu kira.",
    "Mulailah dari sekarang, bukan nanti.",
    "Percaya pada dirimu sendiri adalah kunci pertama menuju kesuksesan.",
    "Rintangan adalah jalan, bukan penghalang.",
    "Belajar dari kemarin, hidup untuk hari ini, harap untuk esok.",
    "Waktu terbaik untuk memulai adalah sekarang.",
    "Kesuksesan tidak datang kepada mereka yang menunggu.",
    "Lakukan yang terbaik, dan hasil akan mengikuti.",
    "Pikiran positif menciptakan kehidupan positif.",
    "Sukses adalah hasil dari keputusan kecil yang dilakukan setiap hari.",
    "Berani mencoba lebih baik daripada diam.",
    "Jangan bandingkan dirimu dengan orang lain.",
    "Terus melangkah, meski perlahan.",
    "Tidak ada kata terlambat untuk menjadi lebih baik.",
    "Bangkit setiap kali terjatuh.",
    "Keberanian adalah kunci untuk membuka pintu kesempatan.",
    "Kepercayaan diri adalah kekuatan terbesarmu.",
    "Fokus pada tujuan, bukan hambatan.",
    "Tantangan adalah peluang untuk tumbuh.",
    "Setiap usaha tidak akan sia-sia.",
    "Yakin bisa, pasti bisa.",
    "Belajarlah dari kegagalan, bukan takut menghadapinya.",
    "Tetap rendah hati saat sukses.",
    "Terus berjuang, meski dunia meragukanmu.",
    "Impian besar dimulai dari langkah kecil.",
    "Keajaiban datang kepada mereka yang tidak menyerah.",
    "Tetap kuat meski badai menghadang.",
    "Jangan takut gagal, takutlah untuk tidak mencoba.",
    "Kegigihan adalah rahasia kesuksesan.",
    "Setiap detik adalah kesempatan baru.",
    "Jadilah pribadi yang lebih baik setiap hari.",
    "Satu-satunya batasan adalah dirimu sendiri.",
    "Pikiran positif adalah awal dari segalanya.",
    "Jangan buang waktumu untuk meragukan dirimu sendiri.",
    "Kesuksesan adalah milik mereka yang berani melangkah.",
    "Lakukan sesuatu hari ini yang akan disyukuri esok.",
    "Kamu tidak akan pernah tahu kalau tidak mencoba.",
    "Kendalikan harimu, atau harimu akan mengendalikanmu.",
    "Berpikir besar, bertindak nyata.",
    "Waktu berjalan, jangan sia-siakan.",
    "Kerja keras hari ini adalah kebahagiaan esok hari.",
    "Jangan hanya bermimpi, wujudkanlah.",
    "Ubah rintangan menjadi tantangan.",
    "Kamu diciptakan untuk hal-hal besar.",
    "Jadilah cahaya di tengah kegelapan.",
    "Keberhasilan adalah perjalanan, bukan tujuan akhir.",
    "Jangan pernah meremehkan kekuatan tekad.",
    "Jika kamu jatuh tujuh kali, bangkit delapan kali.",
    "Semangatmu adalah bahan bakar suksesmu.",
    "Setiap kesulitan melatih kekuatanmu.",
    "Fokus pada solusi, bukan masalah.",
    "Bersyukurlah, dan teruslah berusaha.",
    "Ketakutan adalah musuh dari pertumbuhan.",
    "Impianmu layak diperjuangkan.",
    "Setiap hari adalah kesempatan untuk memulai lagi.",
    "Kesuksesan dimulai dari keberanian mengambil langkah pertama.",
    "Hidupmu berharga, buat itu berarti.",
    "Keajaiban terjadi saat kamu tidak menyerah.",
    "Masa depanmu ditentukan oleh tindakanmu hari ini.",
    "Selalu ada jalan bagi yang berusaha.",
    "Kamu bisa lebih dari yang kamu bayangkan.",
    "Jangan hanya hidup, tapi tumbuhlah.",
    "Belajar bukan beban, tapi investasi.",
    "Setiap langkah kecil tetap membawa kita maju.",
    "Jangan berhenti saat lelah, berhentilah saat selesai.",
    "Teguhkan hati, kuatkan niat.",
    "Kemenangan dimulai dari pikiran yang yakin.",
    "Kegagalan adalah batu loncatan, bukan tembok penghalang.",
    "Selalu ada pelajaran dalam setiap kegagalan.",
    "Optimisme adalah kunci kebahagiaan.",
    "Jangan takut berubah demi kebaikan.",
    "Mimpi tidak akan bekerja kecuali kamu melakukannya.",
    "Kembangkan potensi, jangan hanya puas.",
    "Hidup bukan soal menunggu badai reda, tapi belajar menari dalam hujan.",
    "Ketika kamu percaya, segalanya menjadi mungkin.",
    "Lakukan sedikit demi sedikit, konsisten lebih penting.",
    "Tak ada kesuksesan tanpa disiplin.",
    "Bersabar adalah kekuatan dalam diam.",
    "Pikiran yang jernih membawa keputusan yang bijak.",
    "Jadilah versi terbaik dari dirimu sendiri.",
    "Jangan biarkan rasa takut mengendalikan langkahmu.",
    "Hidup adalah tentang pertumbuhan, bukan kesempurnaan.",
    "Tekad kuat mengalahkan segalanya.",
    "Sukses bukan milik orang pintar, tapi milik orang tekun.",
    "Tetap fokus pada tujuan, jangan teralihkan.",
    "Berbuat baik itu gratis, lakukan sebanyak mungkin.",
    "Berani gagal adalah tanda kekuatan.",
    "Konsistensi membentuk karakter.",
    "Jangan menunda, lakukan sekarang juga.",
    "Selalu berikan yang terbaik, di mana pun kamu berada.",
    "Apa pun yang kamu pikirkan, kamu bisa mencapainya.",
    "Hargai setiap proses dalam hidupmu.",
    "Kamu sedang tumbuh, meski belum terlihat hasilnya.",
    "Beri waktu untuk dirimu berkembang.",
    "Usaha tidak pernah mengkhianati hasil.",
    "Bersyukur membuat hidup lebih bahagia.",
    "Rencana besar dimulai dari keberanian kecil.",
    "Semua orang bisa sukses jika mereka mau berusaha.",
    "Jangan takut menonjol, kamu unik.",
    "Jangan berhenti sampai kamu bangga.",
    "Lebih baik mencoba daripada menyesal tak pernah mencoba.",
    "Percaya proses, jangan buru-buru.",
    "Bersikap positif menarik hal-hal positif.",
    "Semangat hari ini menentukan hasil esok hari.",
    "Terus belajar dan terus bertumbuh.",
    "Sukses itu perjalanan, bukan tujuan akhir.",
    "Setiap kesalahan adalah pelajaran berharga.",
    "Tetap semangat walau dalam tekanan.",
    "Kamu bisa jadi apapun yang kamu mau.",
    "Tak ada hasil tanpa pengorbanan.",
    "Buktikan dirimu melalui tindakan, bukan kata-kata.",
    "Terus berjuang, kamu hampir sampai.",
    "Ketika lelah, ingat tujuan awalmu.",
    "Tidak ada kerja keras yang sia-sia.",
    "Percayalah, kamu cukup.",
    "Semua hal besar dimulai dari keputusan berani.",
    "Yakin dan terus melangkah.",
    "Sukses adalah tentang tetap berjalan saat orang lain berhenti.",
    "Keberanian mengubah segalanya.",
    "Jadilah pemimpin dalam hidupmu sendiri.",
    "Hidupmu adalah tanggung jawabmu.",
    "Terus belajar, terus berkembang.",
    "Bangkit dan lawan rasa malas.",
    "Mulailah hari dengan niat baik.",
    "Apa pun yang terjadi, jangan menyerah.",
    "Kamu lebih kuat dari masalahmu.",
    "Jangan biarkan masa lalu menghambat masa depanmu.",
    "Buat hari ini lebih baik dari kemarin.",
    "Tujuan besar butuh kerja keras nyata.",
    "Lakukan apa yang kamu bisa, dengan yang kamu punya.",
    "Berikan alasan untuk dirimu percaya diri.",
    "Impianmu butuh aksi nyata, bukan hanya angan.",
    "Tindakan hari ini menentukan keberhasilan esok.",
    "Kamu pejuang, bukan pecundang.",
    "Tak ada batas untuk belajar dan tumbuh.",
    "Milikilah semangat pantang menyerah.",
    "Terus berusaha meski hasil belum terlihat.",
    "Hidup ini tentang bagaimana kamu bangkit.",
    "Setiap hari adalah awal baru.",
    "Semua mimpi bisa terwujud dengan usaha.",
    "Kamu pantas untuk sukses.",
    "Jangan biarkan rasa takut mengalahkan impianmu.",
    "Satu langkah lebih baik dari diam.",
    "Perubahan dimulai dari dirimu.",
    "Lakukan yang terbaik, sisanya biar Tuhan yang urus.",
    "Setiap usaha adalah bentuk cinta pada diri sendiri.",
    "Percaya bahwa segala sesuatunya akan membaik.",
    "Hidup hanya sekali, jangan sia-siakan.",
    "Lakukan dengan hati, hasil akan mengikuti.",
    "Jangan takut gagal, takutlah untuk tidak mencoba.",
    "Semua orang memulai dari nol.",
    "Keberhasilan adalah hak semua orang yang mau berjuang.",
    "Kamu mampu menghadapi semua ini.",
    "Terus melangkah, sukses semakin dekat.",
]


function motivasi(){
  const tampilan = document.querySelector("p");
  let a = Math.floor(Math.random()* text.length);
  tampilan.innerHTML = text[a];
}


function jam() {
  const tampilan = document.querySelector("h2");
  const waktu = new Date();
  const jam = waktu.getHours();
  const menit = waktu.getMinutes();
  const detik = waktu.getSeconds();
  const mdetik = waktu.getMilliseconds();
  tampilan.innerHTML = jam + ":" + menit + ":" + detik + ":" + mdetik;
}
setInterval(jam,1);
